### ISSUE TITLE
[JOSS REVIEW] Automated tests

### ISSUE THREAD

**Issue by yjunechoe** [sportiellomike/mousebreedeR#1]
The **Automated tests** checklist for the JOSS review asks:

> Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

I don't think I see one set up for this package - if I'm incorrect about this, could you point me to where automated testing/checking exists?

Otherwise, I suggest setting up github actions to run the **R CMD check**. This takes a single line of code (read [R Packages Ch.20](https://r-pkgs.org/software-development-practices.html#r-cmd-check-via-gha) for more)

```r
usethis::use_github_action()
```

Relatedly, **please resolve** all _ERRORs_ and _WARNINGs_ that you encounter during **R CMD check**, to help facilitate the rest of the review. It's okay for the package to trigger some of the less critical _NOTEs_ if you do not have a plan on submitting it to CRAN.

On my end, when I run the check locally with `devtools::check()`, I see the following problems:

<details>
<summary>Problems</summary>
<pre>
── R CMD check results ───────────────────── mousebreedeR 0.1.0 ────
Duration: 39.1s

❯ checking examples ... ERROR
  Running examples in 'mousebreedeR-Ex.R' failed
  The error most likely occurred in:
  
  &gt; base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  &gt; ### Name: addpoints
  &gt; ### Title: addpoints
  &gt; ### Aliases: addpoints
  &gt; 
  &gt; ### ** Examples
  &gt; 
  &gt; addpoints(x,desiredvector=exampledesiredvec)
  Error: object 'x' not found
  Execution halted

❯ checking tests ...
  See below...

❯ checking whether package 'mousebreedeR' can be installed ... WARNING
  See below...

❯ checking Rd files ... WARNING
  prepare_Rd: grapes-not-in-grapes.Rd: \name should not contain !, | or @

❯ checking for missing documentation entries ... WARNING
  Undocumented code objects:
    'examplecanwegetalltheallelesfromonecross'
    'examplecompilegametesoutput' 'exampledesiredvec' 'exampleeggs'
    'exampleexampleData' 'examplefertilizeoutput' 'examplemeiosisoutput'
    'examplepointsperpupoutput' 'examplesperm'
    'examplesummarizefertilizationoutput'
    'examplesummarizepotentialpupoutput' 'examplewhichpairstobreed'
    'female' 'genotypevalschar' 'het' 'hetchar' 'hetorhomopos' 'homoneg'
    'homonegchar' 'homopos' 'homoposchar' 'male'
  Undocumented data sets:
    'examplecanwegetalltheallelesfromonecross'
    'examplecompilegametesoutput' 'exampledesiredvec' 'exampleeggs'
    'exampleexampleData' 'examplefertilizeoutput' 'examplemeiosisoutput'
    'examplepointsperpupoutput' 'examplesperm'
    'examplesummarizefertilizationoutput'
    'examplesummarizepotentialpupoutput' 'examplewhichpairstobreed'
    'female' 'genotypevalschar' 'het' 'hetchar' 'hetorhomopos' 'homoneg'
    'homonegchar' 'homopos' 'homoposchar' 'male'
  All user-level objects in a package should have documentation entries.
  See chapter 'Writing R documentation files' in the 'Writing R
  Extensions' manual.

❯ checking for code/documentation mismatches ... WARNING
  Codoc mismatches from documentation object '%!in%':
  %!in%
    Code: function(...)
    Docs: function(..., NA)
    Argument names in docs not in code:
      NA

❯ checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object '%!in%'
    '...' 'NA'
  
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter 'Writing R documentation files' in the 'Writing R
  Extensions' manual.

❯ checking for unstated dependencies in 'tests' ... WARNING
  'library' or 'require' call not declared from: 'tidyverse'

❯ checking for hidden files and directories ... NOTE
  Found the following hidden files and directories:
    .github
  These were most likely included in error. See section 'Package
  structure' in the 'Writing R Extensions' manual.

❯ checking DESCRIPTION meta-information ... NOTE
  Malformed Title field: should not end in a period.

❯ checking top-level files ... NOTE
  Non-standard files/directories found at top level:
    'data-raw' 'paper.bib' 'paper.md'

❯ checking dependencies in R code ... NOTE
  Namespaces in Imports field not imported from:
    'dplyr' 'dqrng' 'ggplot2' 'ggpubr' 'gtools' 'reshape2' 'viridis'
    All declared Imports should be used.

❯ checking R code for possible problems ... NOTE
  addpoints: no visible binding for global variable 'desiredvec'
  canwegetalltheallelesfromonecross: no visible binding for global
    variable 'desiredvec'
  canwegetalltheallelesfromonecross: no visible binding for global
    variable 'homopos'
  canwegetalltheallelesfromonecross: no visible binding for global
    variable 'het'
  canwegetalltheallelesfromonecross: no visible binding for global
    variable 'genotypevalschar'
  compilegametes: no visible global function definition for '%&gt;%'
  compilegametes: no visible global function definition for 'count'
  compilegametes: no visible binding for global variable 'mouseID'
  compilegametes: no visible global function definition for
    'permutations'
  compilegametes: no visible global function definition for 'bind_rows'
  compilegametes: no visible global function definition for 'na.omit'
  engageinmeiosis: no visible binding for global variable 'homopos'
  engageinmeiosis: no visible binding for global variable 'homoneg'
  engageinmeiosis: no visible binding for global variable 'het'
  fertilize: no visible binding for global variable 'sperm'
  fertilize: no visible binding for global variable 'eggs'
  fertilize: no visible global function definition for 'bind_rows'
  fertilize: no visible binding for '&lt;&lt;-' assignment to 'fertilizeoutput'
  pointsperpup: no visible binding for global variable 'desiredvec'
  pointsperpup: no visible binding for global variable 'genotypevalschar'
  possiblepointsfromdesiredoutcome: no visible binding for global
    variable 'desiredvec'
  spermandeggs: no visible binding for global variable 'male'
  spermandeggs: no visible binding for global variable 'female'
  summarizefertilization: no visible global function definition for
    'bind_rows'
  summarizepotentialpups: no visible global function definition for
    'aggregate'
  summarizepotentialpups: no visible global function definition for
    'bind_rows'
  whichpairsshouldibreed: no visible binding for global variable
    'pointsperpupoutput'
  whichpairsshouldibreed: no visible binding for global variable
    'desiredvec'
  whichpairsshouldibreed: no visible binding for global variable
    'fertilizeoutput'
  Undefined global functions or variables:
    %&gt;% aggregate bind_rows count desiredvec eggs female fertilizeoutput
    genotypevalschar het homoneg homopos male mouseID na.omit
    permutations pointsperpupoutput sperm
  Consider adding
    importFrom("stats", "aggregate", "na.omit")
  to your NAMESPACE file.

❯ checking for non-standard things in the check directory ... NOTE
  Found the following files/directories:
    ''NULL''

── Test failures ───────────────────────────────────── testthat ────

&gt; # This file is part of the standard setup for testthat.
&gt; # It is recommended that you do not modify it.
&gt; #
&gt; # Where should you do additional test configuration?
&gt; # Learn more about the roles of various files in:
&gt; # * https://r-pkgs.org/testing-design.html#sec-tests-files-overview
&gt; # * https://testthat.r-lib.org/articles/special-files.html
&gt; 
&gt; library(testthat)
&gt; library(mousebreedeR)
&gt; 
&gt; test_check("mousebreedeR")

Attaching package: 'dplyr'

The following object is masked from 'package:testthat':

    matches

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

[ FAIL 4 | WARN 0 | SKIP 0 | PASS 0 ]

══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-compilegametes.R:6:3'): gametes compile ────────────────────────
&lt;packageNotFoundError/error/condition&gt;
Error in `library(tidyverse)`: there is no package called 'tidyverse'
Backtrace:
    ▆
 1. └─base::library(tidyverse) at test-compilegametes.R:6:3
── Error ('test-fertilize.R:6:3'): fertilization works ─────────────────────────
&lt;packageNotFoundError/error/condition&gt;
Error in `library(tidyverse)`: there is no package called 'tidyverse'
Backtrace:
    ▆
 1. └─base::library(tidyverse) at test-fertilize.R:6:3
── Error ('test-meiosis.R:6:3'): meiosis works ─────────────────────────────────
&lt;packageNotFoundError/error/condition&gt;
Error in `library(tidyverse)`: there is no package called 'tidyverse'
Backtrace:
    ▆
 1. └─base::library(tidyverse) at test-meiosis.R:6:3
── Error ('test-onecross.R:6:3'): one cross function works ─────────────────────
&lt;packageNotFoundError/error/condition&gt;
Error in `library(tidyverse)`: there is no package called 'tidyverse'
Backtrace:
    ▆
 1. └─base::library(tidyverse) at test-onecross.R:6:3

[ FAIL 4 | WARN 0 | SKIP 0 | PASS 0 ]
Error: Test failures
Execution halted

2 errors ✖ | 6 warnings ✖ | 6 notes ✖
</pre>
</details>

**Comment by sportiellomike** [comment]
Understood. Will work on solving this weekend. Will tag you once fixed. Apologies for the delay, I was waiting for some notification for your total list of proposed changes, but am happy to work this way with you as well.

**Comment by yjunechoe** [comment]
Thanks for taking this feedback into account. I would normally do a full round of review first, but as you're aware the editors are evaluating scope of your submission on the substantial scholarly effort criterion.

And actually, I want to clarify on this point further here since I don't think I made it clear over at the review thread. The fundamental issue is that the package is fairly small in terms of LOC (lines of code). This is of course not the *only* review criteria, but the journal's [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) state:

> As a rule of thumb, JOSS’ minimum allowable contribution should represent not less than three months of work for an individual. Some factors that may be considered by editors and reviewers when judging effort include:
> ...
> - Total lines of code (LOC). Submissions under 1000 LOC will usually be flagged, those under 300 LOC will be desk rejected.

In case you are not aware of recent history, JOSS [has become increasingly strict](https://blog.joss.theoj.org/2020/07/minimum-publishable-unit) on this point. Given this track record, I believe that the editors may have simply forgotten to query scope your pre-review submission (these days, <1k are usually desk rejected). Coupled with the LOC dropping substantially between ~1k at pre-review and ~300 at review (presumably due to the thinning down of test scripts, which is technically not part of LOC anyways), I had to notify them during my review as per [reviewer guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#substantial-scholarly-effort). This is ultimately determined by the editorial board and their decision is what I'm currently waiting on to proceed with the rest of the review.

In sum, **I urge you to make a case over at the review thread** on why LOC should not be considered as heavily for your submission (perhaps you had taken extra steps to ensure that your code was space-efficient) and/or why LOC is actually larger than it seems (perhaps you have related work to this package but in a separate repo). I understand that LOC may appear to be a trivial concern to a researcher evaluating their own pet project, but the journal takes this seriously, so I strongly suggest that you address this issue _directly_ for the editors to consider, before they make a judgment.

**Comment by sportiellomike** [comment]
- Big thanks to you and other reviewer. I've read a lot and have learned in this process. 
- I believe I have appropriately added the text to read me as proposed when running suggested lines of code
- I still am getting 1 error in the examples that can't use the %>% function for some reason? I'm less familiar with examples so I'm not sure the path forward here. Given the nature of the package being a linear vignette sequence, are examples needed as the whole vignette is the example and the order of functions is predetermined?
- The warnings seem to be related just to my %!in% function [negate(%in%)], which has always worked fine. I think the other warnings are just documenting the datasets created for the sole purpose of trying to get the actual examples working, previously discussed. 
- About to comment on other thread with updates

**Comment by yjunechoe** [comment]
> I still am getting 1 error in the examples that can't use the %>% function for some reason?

This likely means that the example is missing a `library(dplyr)` at the top.

> Given the nature of the package being a linear vignette sequence, are examples needed as the whole vignette is the example and the order of functions is predetermined?

I think it'd be nice to at least see what the input and output *of each function* should look like. Could examples minimally contain a piece of code such that, when run, it shows the structure of the expected input and output of the function in the console? For example:

```r
# Input to `my_function()`, which is a vector/dataframe/etc. representing ...
# - This is the value returned by `prev_function()`
print(input)

# `my_function()` takes the input and does XYZ
output <- my_function(input)

# Output of `my_function()`, which is a vector/dataframe/etc. representing ...
# - This is the value to be consumed by `next_function()`
print(output)
```

> The warnings seem to be related just to my %!in% function [negate(%in%)], which has always worked fine. I think the other warnings are just documenting the datasets created for the sole purpose of trying to get the actual examples working, previously discussed.

I'm fine with ignoring the warnings for now - they're likely using a stricter standard for a CRAN submission.

**Comment by sportiellomike** [comment]
Fixed relevant issues.
