### ISSUE TITLE
[JOSS REVIEW] Community guidelines

### ISSUE THREAD

**Issue by yjunechoe** [sportiellomike/mousebreedeR#3]
The **Community guidelines** checklist states:

>  Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

This is simple to set up for a GitHub repository - you can create a markdown file in `.github/CODE_OF_CONDUCT.md` and write information addressing each point in the checklist therein.

If you want a jumpstart, you can run the following to get template "code of conduct" and "contributing" files and edit them accordingly.

```r
usethis::use_tidy_contributing()
usethis::use_tidy_coc()
```

**Comment by sportiellomike** [comment]
I am working on these issues and will tag you when resolved. As you mentioned, this will take some time. I appreciate your patience. This is an easier fix, so imagine I can get this done sooner than other suggestions. Thank you.
